stages:
  - build
  - test
  - publish

build:
  stage: build
  script:
    - npm-register -s @temando ${NPM_INSTALL_TOKEN}
    - yarn
    - npm run clean
    - npm run build
  artifacts:
    paths:
      - node_modules/
      - bin/
    expire_in: 1 week
  tags:
    - lambda-nodejs

lint:
  stage: test
  script:
    - npm run lint
  tags:
    - lambda-nodejs

mocha:
   stage: test
   script:
     - npm run test:coverage
   tags:
     - lambda-nodejs

npm:
  stage: publish
  script:
    - npm-register -s @temando ${NPM_PUBLISH_TOKEN}
    - npm publish .
  environment:
    name: npm
    url: "https://www.npmjs.com/package/@temando/gitlab-ci-variables-cli"
  only:
    - tags@developer-experience/gitlab-ci-variables-cli
  tags:
    - lambda-nodejs
